# Generated by Django 4.1 on 2022-08-29 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_homemessage_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemessage',
            name='my_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
