# Generated by Django 4.1 on 2022-08-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='From')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='To')),
            ],
            options={
                'verbose_name': 'HomeMessage',
                'verbose_name_plural': 'HomeMessage',
            },
        ),
    ]
